src/blog_2610/blog/urls.py
from django.urls import path
from . import views
from django import urls

app_name = 'blog'

urlpatterns = [

    #path('', views.index, name='index'),
    #path('detail', views.DetailView.as_view(), name = 'detail'),
    path('index', views.bio, name='index'),
    path('techtips', views.techtips, name='techtips'),
    path('', views.BiohomeView, name = 'biohome'),
    path('archive', views.ArchiveView, name = 'archive'),
    path('biohome/<int:question_id>', views.BlogDetailView, name='blog_detail'),
    path('<int:question_id>/add_comment/', views.add_comment, name='add_comment'),
    path('init', views.init, name='init'),
    #path('biohome/add_comment', views.add_comment, name='add_comment'),  # NEW MAPPING!
]

src/blog_2610/blog_2610/urls.py
from django.contrib import admin
from django.conf.urls import include, url
from django.urls import path
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
#from django.conf.urls import include

urlpatterns = [
    path('blog/', include('blog.urls')),
    path('admin/', admin.site.urls),
]

urlpatterns += staticfiles_urlpatterns()

src/blog_2610/blog/models.py
from django.db import models
# Create your models here.

class Blog(models.Model):
    title = models.CharField(max_length=30) #user designated title
    author_name = models.CharField(max_length=30) #who posted it
    content = models.TextField(max_length=500) # what is actually in the blog post
    date_posted = models.DateTimeField(auto_now_add=True) #this is going to add the current date/time of when the post
                                                    #was created to our blog post
    #pub_date = models.DateTimeField("date published")
    def __str__(self):
        return self.title

class Comments(models.Model):
    blog_id = models.ForeignKey(Blog, on_delete=models.CASCADE)
    content = models.TextField(max_length=500)
    commenter = models.CharField(max_length=30)
    email_address = models.EmailField(blank = True)
    date_posted = models.DateTimeField(auto_now_add=True)
    class Meta:
        ordering = ('-date_posted',)
    def __str__(self):
        return self.commenter





    #Want to add something to check that the emdateail they enter is valid,
    #something like try:
    #validate_email("foo.bar@baz.qux")
#except ValidationError as e:
   # print "oops! wrong email"
#else:
   # print "hooray! email is valid"
   #which seems to be secure, and I think would be a cool validation to have

src/blog_2610/blog/forms.py
from django import forms
from blog.models import Comments

class CommentForm(forms.ModelForm):
    content = forms.CharField(widget=forms.Textarea(attrs={'cols': 70, 'rows': 10}), help_text= "Comment")
    commenter = forms.CharField(max_length= 100, help_text= "Your Name")
    email_address = forms.CharField(max_length= 100,  help_text= "Your Email Address")
    class Meta:
        model = Comments
        fields = ['content', 'commenter',
                      'email_address']

src/blog_2610/blog/views.py
from django.shortcuts import render, render_to_response
from django.http import HttpResponse, Http404, HttpResponseRedirect
import datetime
from .models import Blog, Comments
from django.template import loader, RequestContext
from django.shortcuts import get_object_or_404, render

#def index(request):
 #   return render(request, 'blog/index.html', {'now': strftime('%c')})
filler = ["Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed quis lacus et enim dapibus fermentum. Proin ultrices, massa eget bibendum accumsan, ante lacus maximus eros, quis auctor nibh ante malesuada elit. Phasellus rutrum condimentum varius. Integer mauris ipsum, facilisis nec aliquam a, aliquet nec massa. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Quisque scelerisque velit augue, nec convallis massa pharetra vitae. Integer tincidunt orci nec nunc lacinia, non suscipit enim vehicula. Quisque a porta sem. In facilisis purus eget pulvinar viverra. Pellentesque in tortor gravida, congue arcu sit amet, efficitur mauris. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Interdum et malesuada fames ac ante ipsum primis in faucibus. Praesent eget vulputate nisi.Praesent vestibulum maximus mauris, nec ultricies ex rutrum sed. Aliquam laoreet nunc at condimentum interdum. Pellentesque ac arcu non enim hendrerit posuere vel vitae magna. Aenean metus arcu, porta vel tempor quis, finibus non ligula. Nulla sit amet purus at felis porta mattis. Proin id arcu velit. Sed mauris purus, vulputate vel blandit nec, pellentesque ut turpis. Donec eu fermentum quam, et efficitur sapien.Donec massa metus, pulvinar id nunc a, ornare maximus lectus. Etiam nec gravida lacus. Praesent faucibus arcu vitae mollis ultrices. Quisque eget elit auctor, varius enim vitae, lacinia nisi.",
          "Vivamus tempus augue eu enim ornare, scelerisque fermentum eros laoreet. Vestibulum quis ligula urna. Cras ac odio vulputate, maximus mauris eu, semper urna. Quisque cursus tortor vitae erat semper eleifend. Donec dapibus ante ac nulla tempus efficitur. Fusce dictum eu nulla et fermentum. Nullam at justo lorem. Ut vitae lorem ut quam vestibulum rutrum. Integer sed risus vitae purus malesuada sodales. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Phasellus sed interdum metus, at tempus est. In hac habitasse platea dictumst. Nam quis maximus felis, nec ornare ante. Aenean ultrices ornare sem id bibendum. Ut blandit eleifend justo, a tempor elit sagittis sed. Nam odio erat, venenatis rhoncus lobortis tristique, aliquet in odio. Aliquam diam dolor, pretium nec tincidunt non, hendrerit tincidunt mi. Suspendisse ut ex metus. Cras ut risus nec enim porttitor posuere. Maecenas viverra nisi metus, vitae condimentum leo rhoncus fringilla. Duis placerat ligula quis aliquet dictum. Sed congue bibendum mauris, eget viverra libero.ed quis semper erat, ac fermentum purus.",
          "Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec ut magna efficitur, vestibulum lorem eu, iaculis lacus. Ut quis lacus eget nibh faucibus tincidunt. Aliquam porttitor felis magna, vitae efficitur augue bibendum sit amet. Proin at facilisis elit. Maecenas vitae nibh ante. Suspendisse pulvinar, turpis ac sagittis placerat, justo nisi molestie ligula, eu egestas turpis massa sed enim. Maecenas porta massa non tortor dictum pharetra. Vestibulum vel aliquam lacus. Donec viverra lobortis mauris nec tincidunt. Praesent lectus felis, maximus vitae urna vitae, cursus elementum dolor. Donec varius ligula a ligula finibus aliquam. Donec malesuada finibus mauris, vitae pharetra dolor tempor eu. Proin molestie volutpat suscipit. In sagittis interdum suscipit. In vel turpis in risus fringilla vestibulum sit amet vestibulum odio. Aliquam placerat eleifend sem, sit amet interdum purus rhoncus sed.",
          "Nullam non laoreet sem. Nullam non consectetur augue. Integer congue venenatis tellus id vehicula. Cras eleifend dignissim sapien. Sed ut diam at eros congue feugiat. In lorem lacus, congue eu posuere in, ullamcorper sed turpis. Ut vel ligula sed erat finibus ultrices quis eget mauris. Pellentesque imperdiet sagittis lacus vel euismod. Nullam urna justo, tempor sit amet nulla quis, venenatis eleifend quam. Donec imperdiet tincidunt mi eget hendrerit. Donec mattis enim in eros accumsan consequat. Mauris rhoncus lorem vitae elit iaculis, eu dapibus nulla efficitur. Praesent porttitor ullamcorper est, quis semper elit hendrerit vitae. Curabitur tempus magna tellus, imperdiet elementum nisl elementum non. Vestibulum nec felis at tortor ultrices consectetur. Fusce ultrices tempus magna. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Donec et imperdiet tellus. Maecenas blandit rhoncus augue, finibus ornare nibh fermentum et. Nulla et sapien quis eros consectetur gravida. Phasellus sit amet urna quis nibh scelerisque ornare. Sed et semper quam. Aliquam nunc orci, porta vitae scelerisque id, ornare eget mauris. Pellentesque tincidunt molestie est et egestas. Nam ac felis eu ligula elementum efficitur. Curabitur id nisl viverra, tristique dolor quis, vestibulum eros. Suspendisse in feugiat ex. Mauris quam nisi, sollicitudin at nibh nec, pellentesque ultricies odio. Vivamus metus felis, dignissim volutpat urna vel, euismod consequat leo. Ut tincidunt risus sit amet elementum varius.Cras rhoncus convallis tempus. Etiam non iaculis nuncCras rhoncus convallis tempus. Etiam non iaculis nunc Cras rhoncus convallis tempus. Etiam non iaculis nuncCras rhoncus convallis tempus. Etiam non iaculis nunc",
          "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed quis lacus et enim dapibus fermentum. Proin ultrices, massa eget bibendum accumsan, ante lacus maximus eros, quis auctor nibh ante malesuada elit. Phasellus rutrum condimentum varius. Integer mauris ipsum, facilisis nec aliquam a, aliquet nec massa. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Quisque scelerisque velit augue, nec convallis massa pharetra vitae. Integer tincidunt orci nec nunc lacinia, non suscipit enim vehicula. Quisque a porta sem. In facilisis purus eget pulvinar viverra. Pellentesque in tortor gravida, congue arcu sit amet, efficitur mauris. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Interdum et malesuada fames ac ante ipsum primis in faucibus. Praesent eget vulputate nisi.Praesent vestibulum maximus mauris, nec ultricies ex rutrum sed. Aliquam laoreet nunc at condimentum interdum. Pellentesque ac arcu non enim hendrerit posuere vel vitae magna. Aenean metus arcu, porta vel tempor quis, finibus non ligula. Nulla sit amet purus at felis porta mattis. Proin id arcu velit. Sed mauris purus, vulputate vel blandit nec, pellentesque ut turpis. Donec eu fermentum quam, et efficitur sapien.Donec massa metus, pulvinar id nunc a, ornare maximus lectus. Etiam nec gravida lacus. Praesent faucibus arcu vitae mollis ultrices. Quisque eget elit auctor, varius enim vitae, lacinia nisi.",
          "Vivamus tempus augue eu enim ornare, scelerisque fermentum eros laoreet. Vestibulum quis ligula urna. Cras ac odio vulputate, maximus mauris eu, semper urna. Quisque cursus tortor vitae erat semper eleifend. Donec dapibus ante ac nulla tempus efficitur. Fusce dictum eu nulla et fermentum. Nullam at justo lorem. Ut vitae lorem ut quam vestibulum rutrum. Integer sed risus vitae purus malesuada sodales. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Phasellus sed interdum metus, at tempus est. In hac habitasse platea dictumst. Nam quis maximus felis, nec ornare ante. Aenean ultrices ornare sem id bibendum. Ut blandit eleifend justo, a tempor elit sagittis sed. Nam odio erat, venenatis rhoncus lobortis tristique, aliquet in odio. Aliquam diam dolor, pretium nec tincidunt non, hendrerit tincidunt mi. Suspendisse ut ex metus. Cras ut risus nec enim porttitor posuere. Maecenas viverra nisi metus, vitae condimentum leo rhoncus fringilla. Duis placerat ligula quis aliquet dictum. Sed congue bibendum mauris, eget viverra libero.ed quis semper erat, ac fermentum purus.",
          "Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec ut magna efficitur, vestibulum lorem eu, iaculis lacus. Ut quis lacus eget nibh faucibus tincidunt. Aliquam porttitor felis magna, vitae efficitur augue bibendum sit amet. Proin at facilisis elit. Maecenas vitae nibh ante. Suspendisse pulvinar, turpis ac sagittis placerat, justo nisi molestie ligula, eu egestas turpis massa sed enim. Maecenas porta massa non tortor dictum pharetra. Vestibulum vel aliquam lacus. Donec viverra lobortis mauris nec tincidunt. Praesent lectus felis, maximus vitae urna vitae, cursus elementum dolor. Donec varius ligula a ligula finibus aliquam. Donec malesuada finibus mauris, vitae pharetra dolor tempor eu. Proin molestie volutpat suscipit. In sagittis interdum suscipit. In vel turpis in risus fringilla vestibulum sit amet vestibulum odio. Aliquam placerat eleifend sem, sit amet interdum purus rhoncus sed.",
          "Nullam non laoreet sem. Nullam non consectetur augue. Integer congue venenatis tellus id vehicula. Cras eleifend"
          ]

filler_names = ["Groghdns Ddong", "Vivamus Tempus", "Orci Varius",  "Jungki Cdhtine", "Ghogudn Sfsts", "Fifhgnt Johofn", "Kofnsi", "ghdafogdfg"]
filler_emails = ["kfgdfgkadjgn@example.com", "dfdsffgadoih@example.com", "djgkjdfga4341@example.com", "dfhdah47665793@example.com"]
filler_titles = ["Gronfodisf", "Ftiereot Igndsdjo", "Hisont", "Adodfngit", "dfdskjfsoudf", "dfsdofissndf", "dsfadoffisod", "dgoigjoij"]

src/blog_2610/blog/templates/blog/Comments_confirm_delete.html
{% extends "base_generic.html" %}

{% block content %}

<h1>Delete Comment</h1>

<p>Are you sure you want to delete the comment: {{ comment }}?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" value="Yes, delete.">
</form>

{% endblock %}

src/blog_2610/blog/templates/blog/Comments_form.html
{% extends "base_generic.html" %}

{% block content %}
  <form action="" method="post">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="Submit">
  </form>
{% endblock %}

src/blog_2610/blog/templates/blog/add_comment.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <title>Comment</title>
		<link rel="stylesheet" href="{% static 'blog/style.css' %}"/>
    </head>

    <body>
        <h3>Post a Comment</h3>
		<div class="form">
        <form id="comment_form" method="post" action="add_comment">
<p>hello world</p>
            {% csrf_token %}
            {% for hidden in form.hidden_fields %}
                {{ hidden }}
            {% endfor %}
{% comment %}
            {% for field in form.visible_fields %}
                {{ field.errors }}
                {{ field.help_text }} </br>
                {{ field }} </br> </br>
            {% endfor %}
			{% endcomment %}

            <input type="submit" name="submit" value="Create Comment" />
        </form>
		</div>
    </body>

</html>

src/blog_2610/blog/templates/blog/archive.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
	<meta charset="utf-8"/>
	<link rel="stylesheet" href="{% static 'blog/style.css' %}"/>
	<title>Honza's Blog</title>
</head>

	<div class = "date">
	It is the {% now "jS \o\f F" %}
	</div>
<div class = center>
	<span class = "link"> 
			<a href="{% url 'blog:index'%}">About Me</a>
	</span>
	<span class = "link"> 
			<a href="{% url 'blog:techtips'%}">Tech Tips</a>
	</span>
	<span class = "link"> 
			<a href=".">Home</a>
	</span>
	<span class = "link"> 
			<a href="{% url 'blog:archive'%}">Archives</a>
	</span>
</div>

<br />

<div class="image">
      <img src="{%static 'blog/pics/honza3v1.jpg' %}" alt="" />
      <h1><span> Blog Archives</span></h1>
</div>
{% if latest_post_list %}
    {% for blog in latest_post_list %}
       <p class = "blogpost">
	    <span style = "float: left;">{{blog.date_posted}}</span></br>
	   <span style = "color: #c6cad1; font-size: 30px;">{{blog.title}} </br></span>{{  blog.content|truncatewords:200  }} </br></br> <span style = "float: right;">Comment Count: 
	   {{ blog.comments_set.count }}</span></p>
    {% endfor %}
{% else %}
    <p>No recent posts are available.</p>
{% endif %}

src/blog_2610/blog/templates/blog/biohome.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
	<meta charset="utf-8"/>
	<link rel="stylesheet" href="{% static 'blog/style.css' %}"/>
	<title>Honza's Blog - Home</title>
</head>
<div class = "date">
	It is the {% now "jS \o\f F" %}
	</div>
<div class = center>
	<span class = "link"> 
			<a href="{% url 'blog:index'%}">About Me</a>
	</span>
	<span class = "link"> 
			<a href="{% url 'blog:techtips'%}">Tech Tips</a>
	</span>
	<span class = "link"> 
			<a href=".">Home</a>
	</span>
	<span class = "link"> 
			<a href="{% url 'blog:archive'%}">Archives</a>
	</span>
</div>

<br />

<div class="image">
      <img src="{%static 'blog/pics/honza3v1.jpg' %}" alt="" />
      <h1><span>Home</span></h1>
</div>

{% if latest_post_list %}
    {% for blog in latest_post_list %}
       <p class = "blogpost">
	    <span style = "float: left;"><a href="{% url 'blog:blog_detail' blog.id %}" style = "color: white;">{{blog.date_posted}}</a></span></br>
	   <span style = "color: #c6cad1; font-size: 30px;">{{blog.title}} </br></span>{{  blog.content|truncatewords:200  }} </br></br> <span style = "float: right;">Comment Count: 
	   {{ blog.comments_set.count }}</span></p>
    {% endfor %}
{% else %}
    <p>No recent posts are available.</p>
{% endif %}

src/blog_2610/blog/templates/blog/blog_detail.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
	<meta charset="utf-8"/>
	<link rel="stylesheet" href="{% static 'blog/style.css' %}"/>
	<title>Honza's Blog - {{blog.title}}</title>
</head>
<div class = "date">
	It is the {% now "jS \o\f F" %}
	</div>
<div class = center>
	<span class = "link"> 
			<a href="{% url 'blog:index'%}">About Me</a>
	</span>
	<span class = "link"> 
			<a href="{% url 'blog:techtips'%}">Tech Tips</a>
	</span>
	<span class = "link"> 
			<a href=".">Home</a>
	</span>
	<span class = "link"> 
			<a href="{% url 'blog:archive'%}">Archives</a>
	</span>
</div>

<h3>{{blog.title}}</h3>
<div class = "personal"> Posted by: {{blog.author_name}} </br>
On: {{blog.date_posted}}</div>
<p class = "blogpost" > {{blog.content}} </p>
{%for comment in blog.comments_set.all%}
<p class = "comment"> {{comment.content}} </br> </br><span style = "float: right;"> {{comment.commenter}},  {{comment.email_address}}</span> </br>
<span style = "float:right;">{{comment.date_posted}}</span></p>
{%endfor%}

        <h3>Post a Comment</h3>
		<div class="form">
        <form id="comment_form" method="post" action="{% url 'blog:add_comment' blog.id %}">
            {% csrf_token %}
			<label for = "Comment"> Comment </label></br>
				<input type = "text", name = "Comment", id = "Comment", style="height:200px;width:500px;"> </br>
				<label for = "Username"> Username </label></br>
				<input type = "text", name = "Username", id = "Username"> </br>
				<label for = "EmailAddress"> Email Address </label></br>
				<input type = "text", name = "EmailAddress", id = "EmailAddress"></br>
            <input type="submit" name="submit" value="Create Comment" />
        </form>
		</div>

src/blog_2610/blog/templates/blog/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
	<meta charset="utf-8"/>
	<link rel="stylesheet" href="{% static 'blog/style.css' %}"/>
	<title>Honza's Blog - About Me</title>
</head>
<div class = "date">
	It is the {% now "jS \o\f F" %}
	</div>
<div class = center>
	<span class = "link"> 
			<a href="{% url 'blog:index'%}">About Me</a>
	</span>
	<span class = "link"> 
			<a href="{% url 'blog:techtips'%}">Tech Tips</a>
	</span>
	<span class = "link"> 
			<a href=".">Home</a>
	</span>
	<span class = "link"> 
			<a href="{% url 'blog:archive'%}">Archives</a>
	</span>
</div>

<br />

<div class="image">
      <img src="{%static 'blog/pics/honza3v1.jpg' %}" alt="" />
      <h1><span>About Me</span></h1>
</div>
<h2> Biography </h2>

<p class = "blogpost" id = "bio">
	<img  class = "inlinepic" src="{%static 'blog/pics/honza1.jpeg'%}" alt="" />
	Etiam enim nulla, ultrices eget aliquam eget, interdum ac odio. Fusce 
	mollis ut leo non viverra. Nunc quis metus in ipsum semper congue sit amet
	eu nunc. Phasellus quam ipsum, malesuada id congue id, convallis non turpis.
	Praesent volutpat orci magna, at sodales neque interdum at. Phasellus sit 
	amet velit vitae purus sodales tincidunt. Ut volutpat iaculis lacus ac
	placerat. Etiam arcu orci, placerat sit amet efficitur sed, imperdiet ac 
	diam. Vivamus ante nisl, semper pellentesque lectus vel, aliquet vulputate
	nunc. Suspendisse laoreet orci eu neque elementum feugiat. Sed eleifend
	fermentum imperdiet. Ut venenatis mollis libero eu imperdiet. Nunc dictum
	arcu mi, eu aliquet lectus ultricies dignissim. Aenean non mi ut magna 
	mattis vestibulum eu et dolor. Ut feugiat sit amet lorem quis mattis. 
	Aliquam laoreet magna non massa venenatis, vitae fringilla ligula 
	efficitur.
	<br/>
	<br/>
	Lorem ipsum dolor sit amet, consectetur adipiscing elit. In ultrices cursus
	pharetra. Sed finibus enim porta, cursus magna non, feugiat nisi. In luctus
	ullamcorper quam quis feugiat. Aliquam erat volutpat. Aliquam pellentesque 
	nisl nec tempus dapibus. Nam gravida dui quis lacus elementum tincidunt sit
	amet non nisi. Sed elementum arcu id aliquam gravida. Quisque elementum at 
	nisl at venenatis.
</p>


<h2 class = "gallery"> Gallery </h2>
<img class = "gallerypics" src="{%static 'blog/pics/honza2.jpeg' %}" alt="" />
<img class ="gallerypics" src="{%static 'blog/pics/ball.png' %}" alt="" />
<img class = "gallerypics" src="{%static 'blog/pics/honzaFence.jpeg' %}" alt="" />
<img class = "gallerypics" src="{%static 'blog/pics/tennis.png' %}" alt="" />

src/blog_2610/blog/templates/blog/techtips.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
	<meta charset="utf-8"/>
	<link rel="stylesheet" href="{% static 'blog/style.css' %}"/>
	<title>Honza's Blog - About Me</title>
</head>
<div class = "date">
	It is the {% now "jS \o\f F" %}
	</div>
<div class = center>
	<span class = "link"> 
			<a href="{% url 'blog:index'%}">About Me</a>
	</span>
	<span class = "link"> 
			<a href="techtips">Tech Tips</a>
	</span>
	<span class = "link"> 
			<a href=".">Home</a>
	</span>
	<span class = "link"> 
			<a href="archive">Archives</a>
	</span>
</div>

<br />

<div class="image">
      <img src="{%static 'blog/pics/honza3v1.jpg' %}" alt="" />
      <h1><span>Tech Tips</span></h1>
</div>
<table>
	<tr>
		<th>Command</th>
		<th>Description</th>
		<th>Example</th>
	</tr>
	<tr>
		<td> <code>git status</code></td>
		<td> <p> This git command is used to check if there have been any untracked 
		changes have been made in your repository without being committed<p></td>
		
<td> <pre><code>(base) C:\Users\arian\CS2610-Bunnell-Arianna-Assn1> git status 
On branch master
Your branch is ahead of 'origin/master' by 26 commits. 
(use "git push" to publish your local commits)</code></pre></td>
	</tr>
	
	<tr>
		<td> <code>git add</code></td>
		<td> <p> This git command is used to add either a file with untracked 
		changes, or a previously untracked file to your git repository<p></td>
		
<td> <pre><code>(base) C:\Users\arian\CS2610-Bunnell-Arianna-Assn1> git add techtips.html</code></pre></td>
	</tr>
	
	<tr>
		<td> <code>git commit</code></td>
		<td> <p> This git command is used to record changes which you have
		made to your local files after you have added them, taking a 
		"snapshot" of the file at that point in time, adding a message to be paired
		with your commit in quotes after the -m <p></td>
		
<td> <pre><code>(base) C:\Users\arian\CS2610-Bunnell-Arianna-Assn1> 
git commit techtips.html -m "sample commit"
[master c91722e] sample commit
1 file changed, 17 insertions(+)</code></pre></td>
	</tr>
	
	<tr>
		<td> <code>git push</code></td>
		<td> <p> This git command is used to take the current state of 
		your local repository and push it, along with its history, to the 
		remote repository, so it can be accessed from other computers<p></td>
		
<td> <pre><code>(base) C:\Users\arian\CS2610-Bunnell-Arianna-Assn1> 
git push https://bitbucket.org/AriannaB/cs2610-bunnell-arianna-assn1
Username for 'https://bitbucket.org': AriannaB
Password for 'https://AriannaB@bitbucket.org':
Enumerating objects: 5, done.
Counting objects: 100% (5/5), done.
Delta compression using up to 4 threads
Compressing objects: 100% (3/3), done.
Writing objects: 100% (3/3), 502 bytes | 125.00 KiB/s, done.
Total 3 (delta 2), reused 0 (delta 0)
To https://bitbucket.org/AriannaB/cs2610-bunnell-arianna-assn1
   673ab33..c91722e  master -> master</code></pre></td>
	</tr>
</table>